package View;


import Controller.UsuarioControl;
import Model.Telefone;
import Model.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author tasso
 */
public class CadastroView extends javax.swing.JFrame {
    //ArrayList <Usuario> ListUsr;
    ArrayList <String[]> ListUsr;
    String modo;    
    public static final int NOME = 0;
    public static final int EMAIL = 1;
    public static final int SENHA = 2;
    public static final int QUANTIDADE = 3; // quantidade de telefones
    public static final int TELEFONES = 4;
    public static final int DDD1 = 5;
    public static final int NUMERO1 = 6;
    public static final int TIPO1 = 7;
    public static final int DDD2 = 8;
    public static final int NUMERO2 = 9;
    public static final int TIPO2 = 10;
    public static final int DDD3 = 11;
    public static final int NUMERO3 = 12;
    public static final int TIPO3 = 13;
    public static final int DDD4 = 14;
    public static final int NUMERO4 = 15;
    public static final int TIPO4 = 16;
    
    public CadastroView() {
        initComponents();
        
        modo = "Navegar";
        ListUsr = new ArrayList<>();
        setLocationRelativeTo(null);
        
        //inicia a tela com os campos e botões de Dados desabilitados
        ManipulaInterface();
        
    }
    
    //TABELA DE USUÁRIOS
    public void LoadTableUsr(){
        Object Colunas[] = {"Nome","Email","Senha","Telefones"};
        DefaultTableModel modelo = new DefaultTableModel(Colunas,0);
        
        for(int i=0; i<ListUsr.size();i++){
            //String telefones = "";
            String nome = ListUsr.get(i)[NOME];
            String email = ListUsr.get(i)[EMAIL];
            String senha = ListUsr.get(i)[SENHA];
            String telefones = ListUsr.get(i)[TELEFONES];
            Object linha[] = {nome,email,senha,telefones};
            modelo.addRow(linha);
        }
        
        tbl_usr.setModel(modelo);
        tbl_usr.getColumnModel().getColumn(0).setPreferredWidth(150);
        tbl_usr.getColumnModel().getColumn(3).setPreferredWidth(400);
    }
    
    //habilita e dasabilita os botões da tela
    public void Habilita_Botoes(boolean N, boolean A, boolean E, boolean S, boolean C){
        btn_novo.setEnabled(N);
        btn_alterar.setEnabled(A);
        btn_excluir.setEnabled(E);
        btn_salvar.setEnabled(S);
        btn_cancelar.setEnabled(C);
    }
    
    //habilita e desabilita campos
    public void Habilita_Campos (boolean C){
        c_nome.setEnabled(C);
        c_email.setEnabled(C);
        c_senha.setEnabled(C);
        c_ddd1.setEnabled(C);
        c_numero1.setEnabled(C);
        c_tipo1.setEnabled(C);
        c_ddd2.setEnabled(C);
        c_numero2.setEnabled(C);
        c_tipo2.setEnabled(C);
        c_ddd3.setEnabled(C);
        c_numero3.setEnabled(C);
        c_tipo3.setEnabled(C);
        c_ddd4.setEnabled(C);
        c_numero4.setEnabled(C);
        c_tipo4.setEnabled(C);
    }
    
    //limpa os campos 
    public void Limpa_Campos (){
        c_nome.setText("");
        c_email.setText("");
        c_senha.setText("");
        c_ddd1.setText("");
        c_numero1.setText("");
        c_tipo1.setText("");
        c_ddd2.setText("");
        c_numero2.setText("");
        c_tipo2.setText("");
        c_ddd3.setText("");
        c_numero3.setText("");
        c_tipo3.setText("");
        c_ddd4.setText("");
        c_numero4.setText("");
        c_tipo4.setText("");
    }

    //trata a habilitação e desabilitação dos botões e dos campos
    public void ManipulaInterface(){
        switch(modo){
            case "Navegar":
                Limpa_Campos();
                Habilita_Botoes(true,false,false,false,false);
                Habilita_Campos(false);
                break;
            case "Novo":
                Limpa_Campos();
                Habilita_Botoes(true,false,false,true,true);
                Habilita_Campos(true);
                break;
            case "Alterar":
                Habilita_Botoes(true,false,false,true,true);
                Habilita_Campos(true);
                break;
            case "Excluir":
                Habilita_Botoes(true,false,false,false,false);
                Habilita_Campos(false);
                break;
            case "Selecao":
                Habilita_Botoes(true,true,true,false,false);
                Habilita_Campos(false);
                break;
            default: System.out.println("Modo Inválido!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usr = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_senha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c_ddd1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        c_numero1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c_tipo1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c_ddd2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        c_numero2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        c_tipo2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        c_ddd3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        c_numero3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        c_tipo3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        c_ddd4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        c_numero4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        c_tipo4 = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JToggleButton();
        btn_cancelar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btn_novo = new javax.swing.JToggleButton();
        btn_alterar = new javax.swing.JToggleButton();
        btn_excluir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_usr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Senhas", "Telefones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_usr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_usr);
        if (tbl_usr.getColumnModel().getColumnCount() > 0) {
            tbl_usr.getColumnModel().getColumn(0).setPreferredWidth(150);
            tbl_usr.getColumnModel().getColumn(3).setPreferredWidth(400);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));

        jLabel2.setText("Nome:");

        c_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Email:");

        jLabel4.setText("Senha:");

        c_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_senhaActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefones:");

        jLabel6.setText("DDD:");

        c_ddd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ddd1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Número:");

        jLabel8.setText("Tipo:");

        jLabel9.setText("DDD:");

        c_ddd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ddd2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Número:");

        jLabel11.setText("Tipo:");

        jLabel12.setText("DDD:");

        c_ddd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ddd3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Número:");

        jLabel14.setText("Tipo:");

        jLabel15.setText("DDD:");

        c_ddd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ddd4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Número:");

        jLabel17.setText("Tipo:");

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_ddd3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_numero3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_ddd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_numero2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_ddd1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_numero1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_senha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_tipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_ddd4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_numero4)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_tipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(c_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(c_ddd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(c_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(c_tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(c_ddd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(c_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(c_tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(c_ddd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(c_numero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(c_tipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(c_ddd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(c_numero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(c_tipo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Usuários");

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btn_novo)
                        .addGap(13, 13, 13)
                        .addComponent(btn_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_excluir))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeActionPerformed

    private void c_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_senhaActionPerformed

    private void c_ddd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ddd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ddd1ActionPerformed

    private void c_ddd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ddd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ddd2ActionPerformed

    private void c_ddd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ddd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ddd3ActionPerformed

    private void c_ddd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ddd4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_ddd4ActionPerformed

    //BOTÃO ALTERAR
    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        modo = "Alterar";
        ManipulaInterface();
    }//GEN-LAST:event_btn_alterarActionPerformed

    //BOTÃO EXCLUIR
    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int index = tbl_usr.getSelectedRow();
        if(index>=0 && index<ListUsr.size()){
            ListUsr.remove(index);
        }
        
        LoadTableUsr();
        modo = "Navegar";
        ManipulaInterface();
    }//GEN-LAST:event_btn_excluirActionPerformed
    
    //BOTÃO SALVAR
    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        
        int index = tbl_usr.getSelectedRow();
        ArrayList <Telefone> ListFone = new ArrayList();
        String usuario[] = new String[17];

        String nome = c_nome.getText();
        String email = c_email.getText();
        String senha = c_senha.getText();

        //assumindo que pelo menos um campo de telefone é preenchido
        String ddd1 = c_ddd1.getText();
        String numero1 = c_numero1.getText();
        String tipo1 = c_tipo1.getText();       

        String telefones;
        telefones = "("+ddd1+")"+numero1+" - "+tipo1;
        String quantidade_telefones = "1";
        if(modo.equals("Novo")){
            usuario[NOME] = nome; 
            usuario[EMAIL] = email;
            usuario[SENHA] = senha;
            usuario[QUANTIDADE] = quantidade_telefones;
            usuario[TELEFONES] = telefones;
            usuario[DDD1] = ddd1;
            usuario[NUMERO1] = numero1;
            usuario[TIPO1] = tipo1;
        } else if(modo.equals("Alterar")){
            ListUsr.get(index)[NOME] = nome;
            ListUsr.get(index)[EMAIL] = email;
            ListUsr.get(index)[SENHA] = senha;
            ListUsr.get(index)[QUANTIDADE] = quantidade_telefones;
            ListUsr.get(index)[TELEFONES] = telefones;
            ListUsr.get(index)[DDD1] = ddd1;
            ListUsr.get(index)[NUMERO1] = numero1;
            ListUsr.get(index)[TIPO1] = tipo1;
        }
        
        //só adiciona a lista ListFone os telefones com campo preechidos
        //verifica se o 2º campo está preenchido
        String numero2 = c_numero2.getText();
        if(!(c_ddd2.getText().equals("")) && !(numero2.equals(""))){
            quantidade_telefones = "2";
            String ddd2 = c_ddd2.getText();
            String tipo2 = c_tipo2.getText();
            telefones = telefones + ", ("+ddd2+")"+numero2+" - "+tipo2;
            
            if(modo.equals("Novo")){
                usuario[DDD2] = ddd2;
                usuario[NUMERO2] = numero2;
                usuario[TIPO2] = tipo2;
            } else if(modo.equals("Alterar")){
                    ListUsr.get(index)[DDD2] = ddd2;
                    ListUsr.get(index)[NUMERO2] = numero2;
                    ListUsr.get(index)[TIPO2] = tipo2;
            }
            usuario[TELEFONES] = telefones;            

            //verifica se o 3º campo está preenchido
            String numero3 = c_numero3.getText();
            if(!(c_ddd3.getText().equals("")) && !(numero3.equals(""))){
                quantidade_telefones = "3";
                String ddd3 = c_ddd3.getText();            
                String tipo3 = c_tipo3.getText();
                telefones = telefones + ", ("+ddd3+")"+numero3+" - "+tipo3;
            
                if(modo.equals("Novo")){
                    usuario[DDD3] = ddd3;
                    usuario[NUMERO3] = numero3;
                    usuario[TIPO3] = tipo3;
                } else if(modo.equals("Alterar")){
                    ListUsr.get(index)[DDD3] = ddd3;
                    ListUsr.get(index)[NUMERO3] = numero3;
                    ListUsr.get(index)[TIPO3] = tipo3;
                }
                usuario[TELEFONES] = telefones;

                //verifica se o 4º campo está preechido
                String numero4 = c_numero4.getText();
                if(!(c_ddd4.getText().equals("")) && !(numero4.equals(""))){
                    quantidade_telefones = "4";
                    String ddd4 = c_ddd4.getText();            
                    String tipo4 = c_tipo4.getText();
                    telefones = telefones + ", ("+ddd4+")"+numero4+" - "+tipo4;
            
                    if(modo.equals("Novo")){
                        usuario[DDD4] = ddd4;
                        usuario[NUMERO4] = numero4;
                        usuario[TIPO4] = tipo4; 
                    } else if(modo.equals("Alterar")){
                        ListUsr.get(index)[DDD4] = ddd4;
                        ListUsr.get(index)[NUMERO4] = numero4;
                        ListUsr.get(index)[TIPO4] = tipo4;
                    }
                    usuario[TELEFONES] = telefones;
                }
            }
        }

        //MVC
        if(UsuarioControl.SalvarUsuario(nome,email,senha,ListFone)){
            this.LoadTableUsr();
            JOptionPane.showMessageDialog(this, "Usuario salvo com sucesso!");
        }else
            JOptionPane.showMessageDialog(this, "Erro ao salvar o usuario!");
        ListUsr.add(usuario);
        LoadTableUsr();
        modo = "Navegar";
        ManipulaInterface();
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    //BOTÃO CANCELAR
    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modo = "Navegar";
        ManipulaInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    //BOTÃO NOVO
    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        modo = "Novo";
        ManipulaInterface();
    }//GEN-LAST:event_btn_novoActionPerformed

    //CLICK NA TABELA
    private void tbl_usrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usrMouseClicked
        int index = tbl_usr.getSelectedRow();
        if(index>=0 && index<ListUsr.size()){ //verifica se o click foi em uma dar linhas da tabela
            String usuario[] = ListUsr.get(index);
            //carrega os campos nome, email e senha
            String nome = usuario[NOME];
            String email = usuario[EMAIL];
            String senha = usuario[SENHA];
            
            c_nome.setText(nome);
            c_email.setText(email);
            c_senha.setText(senha);
            
            c_ddd1.setText(ListUsr.get(index)[DDD1]);
            c_numero1.setText(ListUsr.get(index)[NUMERO1]);
            c_tipo1.setText(ListUsr.get(index)[TIPO1]);
            //verifica se há outros números
            int quantidade_telefones = Integer.parseInt(ListUsr.get(index)[QUANTIDADE]);
            if(quantidade_telefones>1){
                c_ddd2.setText(ListUsr.get(index)[DDD2]);
                c_numero2.setText(ListUsr.get(index)[NUMERO2]);
                c_tipo2.setText(ListUsr.get(index)[TIPO2]);
                
                if(quantidade_telefones>2){
                    c_ddd3.setText(ListUsr.get(index)[DDD3]);
                    c_numero3.setText(ListUsr.get(index)[NUMERO3]);
                    c_tipo3.setText(ListUsr.get(index)[TIPO3]);
                    
                    if(quantidade_telefones>3){
                        c_ddd4.setText(ListUsr.get(index)[DDD4]);
                        c_numero4.setText(ListUsr.get(index)[NUMERO4]);
                        c_tipo4.setText(ListUsr.get(index)[TIPO4]);
                    } else{
                        c_ddd4.setText("");
                        c_numero4.setText("");
                        c_tipo4.setText("");
                    }
                } else{
                    c_ddd3.setText("");
                    c_numero3.setText("");
                    c_tipo3.setText("");
                }
            } else{
                c_ddd2.setText("");
                c_numero2.setText("");
                c_tipo2.setText("");
            }
            
            modo = "Selecao";
            ManipulaInterface();
        }
    }//GEN-LAST:event_tbl_usrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_alterar;
    private javax.swing.JToggleButton btn_cancelar;
    private javax.swing.JToggleButton btn_excluir;
    private javax.swing.JToggleButton btn_novo;
    private javax.swing.JToggleButton btn_salvar;
    private javax.swing.JTextField c_ddd1;
    private javax.swing.JTextField c_ddd2;
    private javax.swing.JTextField c_ddd3;
    private javax.swing.JTextField c_ddd4;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_numero1;
    private javax.swing.JTextField c_numero2;
    private javax.swing.JTextField c_numero3;
    private javax.swing.JTextField c_numero4;
    private javax.swing.JTextField c_senha;
    private javax.swing.JTextField c_tipo1;
    private javax.swing.JTextField c_tipo2;
    private javax.swing.JTextField c_tipo3;
    private javax.swing.JTextField c_tipo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_usr;
    // End of variables declaration//GEN-END:variables
}
